### ISSUE TITLE
Missing systemjs.config.js file ?

### ISSUE THREAD

**Issue by MerlinMartel** [maliksahil/Angular2AzureAD#1]
Hi Malik,

thx for sharing this, will help me a lot !

I did the npm install and npm start, and it seems to miss the file systemjs.config.js in the project.

Let me know if I do something wrong.

MM

**Comment by maliksahil** [comment]
I forgot to check that in .. all checked in now .. do you mind retrying?

**Comment by MerlinMartel** [comment]
Now the app is building!, thx for the fast anwser.

**Comment by MerlinMartel** [comment]
I tested the application, working well !
My documents are loaded.
thx

**Comment by maliksahil** [comment]
Yay! Share the love :) .. write something cool .. share it with the world. No?
